torchrun --nproc_per_node=4 scripts/distill_whole_model.py \
                --model-config-path 'data/MobileLLM/config.json' \
                --model-weights-path 'data/MobileLLM/model.safetensors' \
                --data-path 'data/minipile' \
                --checkpoint-dir 'checkpoints_full_model' \
                --from_checkpoint 'checkpoints/checkpoint_step_601.pt' \
                --val 'test' \
                --device 'cuda' \
                --max-steps 20000 \
                --batch-size 16 \
                --seq-length 512 \
                --gradient-accumulation-steps 4 \
                --learning-rate 1e-3 \
                --min-learning-rate 1e-5 \
                --weight-decay 1e-5 \
                --grad-clip 1.0 \
                --alpha 0.5 \
                --temperature 2.0 \
                --loss-chunk-size 1024 \
                --use-amp \
                --amp-dtype 'bfloat16' \
                --log-interval 10 \
                --save-interval 1000 \
                --val-interval 250 \
                --val-batches 10 \
                --factorization-rank 16 \
                --layer-sharing
                
